# Generated by Django 2.1.4 on 2019-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField(auto_now=True)),
            ],
        ),
    ]
