# Generated by Django 2.1.4 on 2019-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
