# Generated by Django 2.1.4 on 2019-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0005_auto_20191120_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_created=True),
        ),
    ]
