# Generated by Django 2.1.4 on 2019-11-20 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0007_auto_20191120_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 21, 27, 19, 919952, tzinfo=utc)),
        ),
    ]
