# Generated by Django 2.1.4 on 2019-11-21 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0009_auto_20191121_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='books'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='events'),
        ),
        migrations.AlterField(
            model_name='excos',
            name='photo',
            field=models.ImageField(upload_to='excos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 12, 25, 22, 260330, tzinfo=utc)),
        ),
    ]
