# Generated by Django 2.1.4 on 2019-11-22 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0010_auto_20191121_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 18, 22, 44, 311646, tzinfo=utc)),
        ),
    ]
