# Generated by Django 2.1.4 on 2019-11-22 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0011_auto_20191122_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='room_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 23, 23, 0, 729732, tzinfo=utc)),
        ),
    ]
