# Generated by Django 2.1.4 on 2019-11-24 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0012_auto_20191123_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
