# Generated by Django 2.1.4 on 2019-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0013_auto_20191124_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcosMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prayer_point', models.TextField(max_length=1000)),
            ],
        ),
    ]
