# Generated by Django 2.1.4 on 2019-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0015_auto_20191127_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadermessage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
