# Generated by Django 2.1.4 on 2019-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0017_excos_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excos',
            name='post',
            field=models.CharField(choices=[('l', 'Leader'), ('gs', 'General Secretary'), ('li', 'Librarian'), ('', 'Not Specified')], default='', max_length=5),
        ),
    ]
