# Generated by Django 2.1.4 on 2019-12-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0018_auto_20191127_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excos',
            options={'ordering': ['-name']},
        ),
    ]
