# Generated by Django 2.1.4 on 2019-12-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0019_auto_20191201_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excos',
            options={'ordering': ['name']},
        ),
    ]
