# Generated by Django 2.1.4 on 2019-12-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0021_auto_20191201_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excos',
            options={'ordering': ['-pk']},
        ),
    ]
