# Generated by Django 2.1.4 on 2019-12-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0022_auto_20191201_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
