# Generated by Django 2.1.4 on 2021-01-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0024_auto_20201211_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excos',
            name='post',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
