# Generated by Django 2.1.4 on 2021-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0025_auto_20210128_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='in front of university chapel', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
