# Generated by Django 2.1.4 on 2021-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0026_auto_20210128_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
