# Generated by Django 2.1.4 on 2021-01-28 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0027_auto_20210128_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 28, 20, 47, 20, 134690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 20, 47, 20, 134690, tzinfo=utc)),
        ),
    ]
