# Generated by Django 2.1.4 on 2021-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0029_auto_20210129_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
