# Generated by Django 2.1.4 on 2021-01-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0032_auto_20210129_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
