# Generated by Django 2.1.4 on 2021-01-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0033_remove_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excos',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='excos',
            name='post',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
