# Generated by Django 2.1.4 on 2021-01-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstudy', '0034_auto_20210130_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excos',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Excos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=500),
        ),
    ]
